# Pre-commit configuration file
# This file specifies hooks to run before each commit

repos:
  # Pre-commit-hooks repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use version 4.3.0 of the hooks
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Check yaml files for parseable syntax
      - id: check-yaml
      # Check json files for parseable syntax
      - id: check-json
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict

  # Black - The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.8  # Specify the Python version

  # Flake8 - Python linter
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: 
          - flake8-docstrings  # Check docstrings
          - flake8-bugbear  # Find likely bugs and design problems
        args: ['--max-line-length=88']  # Set maximum line length

  # MyPy - Static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: ['types-setuptools']
        args: 
          - '--ignore-missing-imports'
          - '--strict'  # Enable strict type checking

  # isort - Python utility to sort imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black']  # Use Black-compatible settings

  # ESLint - JavaScript/TypeScript linter
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        args: ['--ext', '.js,.jsx,.ts,.tsx']  # Lint JS, JSX, TS, and TSX files

  # yamllint - YAML linter
  - repo: https://github.com/pre-commit/mirrors-yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  # Additional yamllint configuration (if needed)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
